version: 1.0.{build}

clone_depth: 1

configuration:
    - Release

os: Visual Studio 2015
image: Visual Studio 2015

platform:
    - x86
    - x64

environment:
    matrix:
        - PYTHON: C:\Python35
          PYTHON_VERSION: 35
        - PYTHON: C:\Python36
          PYTHON_VERSION: 36
        - PYTHON: C:\Python37
          PYTHON_VERSION: 37

matrix:
    fast_finish: true

install:
    - IF DEFINED PYTHON (IF "%platform%" == "x64" SET PYTHON=%PYTHON%-x64)
    - IF DEFINED PYTHON SET PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
    - IF DEFINED PYTHON pip install pytest
                                    pytest-runner
                                    setuptools
                                    pybind11
                                    hypothesis

before_build:
    - IF "%platform%" == "x64" set W64="-GVisual Studio 14 2015 Win64"

build_script:
    - mkdir build
    - ps: pushd build
    - cmake %APPVEYOR_BUILD_FOLDER%
            %W64%
            -DCMAKE_CXX_FLAGS=/D_CRT_SECURE_NO_WARNINGS
    - cmake --build .
            --config %configuration%
    - ps: popd

test_script:
    - ps: pushd build
    - ctest --build-config %configuration% --output-on-failure
    - ps: popd
